name: Exercicio

on:
  push:
    branches: [xxx]
    
jobs:
  jobs1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: date
  jobs2:
    name: Job 2
    runs-on: windows-latest
    steps:
      - name: Step two
        run: date
  jobs3:
    name: Job 3
    runs-on: macos-latest
    steps:
      - name: Step three
        run: date
  jobs4:
    name: Job 4
    runs-on: ubuntu-latest
    needs: [jobs1, jobs2, jobs3]
    steps:
      - name: Step four
        run: date
