name: First workflow

on:
  push:
    branches: [main]
    
jobs:
  jobs1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2.3.4
      - name: Step two
        run: env | sort
  jobs2:
    name: Job 2
    runs-on: windows-latest
    needs: jobs1
    steps:
      - name: Step one
        uses: actions/checkout@v2.3.4
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Nme"
